settings:
  APP_DISPLAY_NAME: sTalk
  PRODUCTION_APP_NAME: sTalk
  APP_GROUP_IDENTIFIER: group.ru.implica.stalk.app
  BASE_BUNDLE_IDENTIFIER: ru.implica.stalk
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: Z44H678J3R
